project:
  type: book
  preview: 
    browser: true

book:
  title: "Waves and Fluids"
  subtitle: "Lecture notes for Spring 2023"
  author: "Gustav Delius"
  date: "01/13/2023"
  abstract: |
    In this module we will explore the dynamics of continuous media, 
    focusing on elementary fluid dynamics and the motion of waves. This lays 
    the foundations for the full development of fluid dynamics in years 3 and 4, 
    as well as for modules on electromagnetism and quantum mechanics. The 
    mathematical techniques of vector calculus are employed and further 
    developed, as are Fourier methods and methods from complex analysis.
  description: Work in progress
  downloads: pdf
  repo-url: https://github.com/gustavdelius/WavesAndFluids/
  repo-branch: master
  repo-actions: edit
  sidebar:
    subtitle: Lecture notes
    tools: 
      - icon: mortarboard-fill
        href: https://maths.york.ac.uk/moodle/course/view.php?id=2497
        text: Moodle page
      - icon: bug-fill
        href: https://forms.gle/w17c19vWnM7wpLpz7
        text: Submit a correction
  chapters:
    - index.qmd
    - part: waves.qmd
      chapters:
      - lecture_01.qmd
      - lecture_02.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    reference-location: margin
    cap-location: margin
    link-external-newwindow: true
  pdf:
    documentclass: scrreport

toc: true
number-sections: true
crossref-eq-prefix: Eq.
