project:
  type: book

book:
  title: "Waves and Fluids"
  author: "Gustav Delius"
  date: "01/13/2023"
  chapters:
    - index.qmd
    - lecture_01.qmd
    - lecture_02.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-location: left
  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex

toc: true
number-sections: true
