# Welcome {.unnumbered}

These are the lecture notes for Waves and Fluids, part of the 2nd year Applied
Maths module at the University of York in Spring 2023. Each chapter in these
notes corresponds to one lecture.

These notes will be periodically revised. Whenever you spot something that is not quite right, please email me at [gustav.delius\@york.ac.uk](mailto:gustav.delius@york.ac.uk) or submit your correction in the correction form at <https://forms.gle/w17c19vWnM7wpLpz7>.

::: {.content-visible unless-format="pdf"}

If you want to print these notes you should download the [pdf version](Waves-and-Fluids.pdf).

:::

This module consists of two topics: Waves and Fluids. In the first half of the term, we will focus on Waves, while in the second half, we will delve into Fluids. The topics are interconnected by their use of partial differential equations to describe real-world phenomena in space and time.

An alternative title for this module could be "Introduction to Continuum Dynamics". It is designed to introduce you to the mathematical modeling and analysis of the behaviour of materials that are treated as continua, or continuous media. Unlike Newtonian Dynamics and Classical Dynamics, which deal with individual particles, Continuum Dynamics deals with emergent phenomena created by the interaction of large numbers of particles. It employs mathematical tools such as partial differential equations.

The concepts and methods presented in Continuum Dynamics form the basis of a large part of Applied Mathematics. You will encounter them again in future Applied Mathematics modules, and they are also used in fields such as biology, ecology, medicine, sociology, and economics. The examples presented in this module are less important than the way of thinking they introduce.

The goal of this module is to equip you with the skills and knowledge to apply mathematics to new phenomena in the real world. In your third and fourth year, you will have the opportunity to deepen this ability through various modules.

Throughout this module, we shall use SI units: length is measured in meters (m), time in seconds (s), mass in kilograms (kg).
