# Surface waves 2
In this lecture we want to study the wave solution that we derived in the
previous lecture. We will first look at the paths that the particles in the
fluid follow. Then we will investigate under what condition the linear
approximation that we made to simplify the surface conditions is valid. Finally
we look at the dispersion in the surface waves.

You find content related to this lecture in the textbooks:

- @acheson sections 3.2 and 3.3
- @paterson section 13.3

## Pathlines
From the velocity potential $\phi$ in @eq-wavephi  we can read off the
components of the velocity field as
$$\begin{split}
u_x&=\partial_x\phi=A\omega e^{k\,y}\cos(kx-\omega t),\\
u_y&=\partial_y\phi=A\omega e^{k\,y}\sin(kx-\omega t).
\end{split}$$ {#eq-wu}
The factor of $e^{k\,y}$ shows us that the velocity decreases exponentially
with depth.

We want to understand how the fluid particles move, i.e., we want
to determine the pathlines. These satisfy
$$
\frac{\underline{x}(t)}{dt}=\underline{u}(\underline{x}(t),t).
$$ {#eq-pl1}
Unfortunately these nonlinear equations are too complicated to solve
analytically. So we linearise. We know from experience that, while
the waves on the surface move over long distances, the particles in
the fluid are not swept away with the wave but only move up and down
and forth and back a little bit. So we write the position of the
particle as
$$
\underline{x}(t)=\bar{\underline{x}}+\hat{\underline{x}}(t),
$$ {#eq-17.3}
where $\bar{\underline{x}}$ is the mean position and the $\hat{\underline{x}}$
are assumed to be small. Substituting this into @eq-pl1  and looking at the
components gives
$$\begin{split}
\frac{d\hat{x}}{dt}&\approx A\omega e^{k\,\bar{y}}\cos(k\bar{x}-\omega t),\\
\frac{d\hat{y}}{dt}&\approx A\omega e^{k\,\bar{y}}\sin(k\bar{x}-\omega t).
\end{split}$$ {#eq-17.4}
This is easy to integrate to
$$\begin{split}
\hat{x}&\approx -A e^{k\,\bar{y}}\sin(k\bar{x}-\omega t),\\
\hat{y}&\approx A e^{k\,\bar{y}}\cos(k\bar{x}-\omega t).
\end{split}$$ {#eq-17.5}
This describes motion counterclockwise around a circle of radius
$A e^{k\,\bar{y}}$ around the mean position. When that radius
is small, the pathlines are close to perfect circles. Closer to the surface
where the radius gets bigger the circle will get deformed a bit.


## Validity of linear approximation

Now that we have the solutions to the linearised surface conditions we
can check under what circumstances the linearisation was a good
approximation. For example in @eq-Kl1  we dropped the
term $u_x\partial_x\eta$. This is a good approximation only if the dropped
term is much smaller in magnitude than the terms that remain. So we need
$$
|u_x\partial_x\eta|\ll|u_y|.
$$ {#eq-17.6}
Substituting our solutions from @eq-wu  and @eq-seta gives
$$
|A\omega e^{k\,\eta}\cos(kx-\omega t)A\,k\sin(kx-\omega t)|
\ll|A\omega e^{k\,\eta}\sin(kx-\omega t)|.
$$ {#eq-17.7}
We can cancel a sin from both sides.
The factors of cosine can be dropped because it only
takes values between $-1$ and $1$. So, after cancellations, the condition
becomes
$$
|A\,k|\ll 1.
$$ {#eq-17.8}
Written in terms of the wavelength $\lambda$ this becomes
$$
A\ll\frac{\lambda}{2\pi}.
$$ {#eq-17.9}
So the amplitude of the wave must be small compared to its
wavelength.
This turns out to be exactly the same condition that we also needed in
our linearisation while deriving the equation for waves on a string in
lecture [-@sec-1].

We made other approximations while we linearised the surface
conditions and we need to check whether they too are valid under
the same circumstances. For example we replaced $u_y(x,\eta,t)$
by $u_y(x,0,t)$. This is a good approximation if
$$
|u_y(x,\eta,t)-u_y(x,0,t)|\ll|u_y(x,0,t)|.
$$ {#eq-17.10}
Substituting our solution gives
$$
|A\omega \left(e^{k\,\eta}-1\right)\sin(kx-\omega t)|
\ll|A\omega \sin(kx-\omega t)|,
$$ {#eq-17.11}
which simplifies to
$$
\left|e^{k\,\eta}-1\right|\ll1.
$$ {#eq-17.12}
This holds if $|k\, \eta|\ll 1$ which in turn holds if $|k\,A|\ll 1$.

I leave it up to you to go through the approximations
that we made in @sec-dyn to verify that they too are good
when $|k\,A|\ll 1$.

## Circular waves

You will have observed that when you drop a pebble into a pond, this creates waves that travel outwards from the disturbance with circular wave crests. We can easily find the solutions describing such circular waves by switching to polar coordinates $r$, $\theta$ for the $x$-$z$ plane such that $x=r\cos\theta$ and $z=r\sin\theta$.

The circular waves we are looking for look the same in all directions, so we
will be looking for solutions for the velocity potential $\phi$ and the surface function $\eta$ that are independent of the $\theta$ coordinate:
$$
\phi = \phi(r,y,t),~~~\eta = \eta(r,t).
$$

The Laplace equation for the velocity potential $\phi$ then becomes
$$
0 = \nabla^2\phi=\frac{1}{r}\partial_r^2(r\phi)+\partial_y^2\phi.
$$ {#eq-Lpolar}

Introducing again the distance $d$ from the surface, $d(r,y,t)=y-\eta(r,t)$,
the kinematic surface condition in these coordinates is
$$\begin{split}
\frac{Dd}{Dt}&=\partial_td+\underline{u}\cdot\underline{\nabla} d=\partial_td+u_r\partial_r d+u_y\partial_y d\\
&=-\partial_t\eta-u_r\partial_r \eta+u_y=0.
\end{split}
$$ {#eq-Kpolar}
After linearisation this reduces to
$$
\partial_t\eta(r,t)=u_y(r,0,t).
$$ {#eq-Kpolar}
This is the same as in the case of Carthesian coordinates, just with $r$ taking
the place of $x$. Similarly the linearised dynamic surface condition becomes
$$
\partial_t\phi(r,0,t)=-g\eta(r,t).
$$ {#eq-Dpolar}
Thus the only difference between the problem of circular waves compared to
the problem of plane waves we studied earlier is that the $\partial_x^2\phi$ term in the
Laplace equation has been replaced by $1/r \partial_r^2(r\phi)$. This motivates
us to make the modified Ansatz
$$
\phi(r,y,t) = f(y)\frac{1}{r}\sin(kr-\omega t).
$$
Substituting this into the Laplace equation -@eq-Lpolar again gives the
equation $f''-k^2f$ and imposing that the solution must stay finite as
$y\to-\infty$ singles out the solution $f(y)=D\,e^{ky}$ for some constant $D$.
Thus
$$
\phi(r,y,t)=D e^{ky}\frac{1}{r}\sin(kx-\omega t)
$$

Substituting this velocity potential into the dynamical surface condition -@eq-Dpolar gives
$$
\eta(r,t)=\frac{\omega\,D}{g}\frac{1}{r}\cos(kr-\omega t)
$$
and then the kinematic surface condition -@eq-Kpolar gives the dispersion
relation
$$
\omega = \sqrt{k\,g}.
$$
This is identical to the dispersion relation for the plane wave solution.
